keys:
  - &user_ethnt age1xgvn6f36rkzmq2kfqx0g2xg90qrpar4hpu6fr8xc3s2kqw6dzqcssnslsv
  - &machine_vm age17xrmv0s924hz7rcm6nu8v9nmsu9lszywgg0mhf6xapgrn434ayss77zjzy
  - &machine_monitor age1crljpsec69z0q6m84pe4vmm62ex443jkzlfy8udxxajl3tpmmfcsea8x5f
  - &machine_builder age1xdsdger7rxqq53l662nmekmt32vchyr35hgy8m92hz3meddxueyqg67rv4
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_vm
          - *machine_monitor
          - *machine_builder

  - path_regex: machines/secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_vm
          - *machine_monitor
          - *machine_builder
