keys:
  - &user_ethnt age1xgvn6f36rkzmq2kfqx0g2xg90qrpar4hpu6fr8xc3s2kqw6dzqcssnslsv
  - &machine_htpc age1zljvw50qm5mmg5ntstw85aj2pnkswquzmn7c72vudsq4gtepde4qu5s0vd
  - &machine_gateway age148ehmkp9ppddzkpxduv8mc0anr2sdvpjl39hfzza9kaq429kaf9q2vm4af
  - &machine_monitor age1dald4x0rn9pn8fq045twgew3yg7p4lf7w4wyjaftf27t5qkfw39s2pcv59
  - &machine_errata age1jusjemzl3lr7w9wqck7yfdxvlwjlujchm9vwkfgg9cxpdkngesnqecwq5u
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_htpc
          - *machine_gateway
          - *machine_monitor
          - *machine_errata

  - path_regex: machines/secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_htpc
          - *machine_gateway
          - *machine_monitor
          - *machine_errata
