keys:
  - &user_ethnt age1xgvn6f36rkzmq2kfqx0g2xg90qrpar4hpu6fr8xc3s2kqw6dzqcssnslsv
  - &machine_htpc age1f5n5qx48ax7hgwvuykcqyf8ef8swj9kfrsvwjqzmayvrprkxr4tqgge3w0
  - &machine_gateway age1pvqwmnu6j5x2ynfe92vhukm2536wus2kf4s0pcchfwnl58ytf4jqyknvhl
  - &machine_monitor age1j47lhuv2l306c4e7rc943p6sz0jeyq2zs04cx409s9wdf9cdzvjsky97xx
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_htpc
          - *machine_gateway
          - *machine_monitor

  - path_regex: machines/secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
          - *machine_htpc
          - *machine_gateway
          - *machine_monitor
