name: "CI"
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          install_url: https://releases.nixos.org/nix/nix-2.4/install
      - uses: cachix/cachix-action@v10
        with:
          name: orchard
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # - uses: lhotari/action-upterm@v1
      - run: nix flake check
